// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/RafaySystems/rafay-prompt/pkg/prompt"
)

var configSetClusterOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--embed-certs", Description: "embed-certs for the cluster entry in kubeconfig"},
}
