// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/paralus/prompt/pkg/prompt"
)

var cordonOptions = []prompt.Suggest{
	{Text: "--dry-run", Description: "If true, only print the object that would be sent, without sending it."},
	{Text: "-l", Description: "Selector (label query) to filter on"},
	{Text: "--selector", Description: "Selector (label query) to filter on"},
}
