// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/RafaySystems/prompt/pkg/prompt"
)

var explainOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--api-version", Description: "Get different explanations for particular API version"},
	prompt.Suggest{Text: "--recursive", Description: "Print the fields of fields (Currently only 1 level deep)"},
}
